<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yixin Cao">
<meta name="dcterms.date" content="2026-04-15">

<title>A/B Testing a Call to Action – Yixin Cao’s website</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Yixin Cao’s website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./hw1_questions.html" aria-current="page"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-ab-test-as-a-statistical-problem" id="toc-the-ab-test-as-a-statistical-problem" class="nav-link" data-scroll-target="#the-ab-test-as-a-statistical-problem">The A/B Test as a Statistical Problem</a></li>
  <li><a href="#simulating-data" id="toc-simulating-data" class="nav-link" data-scroll-target="#simulating-data">Simulating Data</a></li>
  <li><a href="#the-law-of-large-numbers" id="toc-the-law-of-large-numbers" class="nav-link" data-scroll-target="#the-law-of-large-numbers">The Law of Large Numbers</a></li>
  <li><a href="#bootstrap-standard-errors" id="toc-bootstrap-standard-errors" class="nav-link" data-scroll-target="#bootstrap-standard-errors">Bootstrap Standard Errors</a></li>
  <li><a href="#the-central-limit-theorem" id="toc-the-central-limit-theorem" class="nav-link" data-scroll-target="#the-central-limit-theorem">The Central Limit Theorem</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a></li>
  <li><a href="#the-t-test-as-a-regression" id="toc-the-t-test-as-a-regression" class="nav-link" data-scroll-target="#the-t-test-as-a-regression">The T-Test as a Regression</a></li>
  <li><a href="#the-problem-with-peeking" id="toc-the-problem-with-peeking" class="nav-link" data-scroll-target="#the-problem-with-peeking">The Problem with Peeking</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A/B Testing a Call to Action</h1>
<p class="subtitle lead">Simulating Key Ideas from Classical Frequentist Statistics</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yixin Cao </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>I have a website where visitors can sign up to receive a newsletter. The landing page includes a call-to-action (CTA) that encourages users to subscribe.</p>
<p>I want to understand which of two different CTAs leads to more sign-ups. CTA A reads “Sign up for our newsletter here!”, while CTA B reads “Stay up to date by signing up!”. Although they aim to achieve the same goal, the wording may influence user behavior.</p>
<p>To compare their effectiveness, I run an A/B test. In this experiment, visitors are randomly assigned to see one of the two CTAs. By comparing the sign-up rates between the two groups, I can determine which version performs better.</p>
</section>
<section id="the-ab-test-as-a-statistical-problem" class="level2">
<h2 class="anchored" data-anchor-id="the-ab-test-as-a-statistical-problem">The A/B Test as a Statistical Problem</h2>
<p>Each visitor either signs up or does not, so we can model each visitor’s outcome as a draw from a Bernoulli distribution with parameter <span class="math inline">\(\pi\)</span>, which represents the probability of signing up.</p>
<p>Because the CTA a visitor sees may influence their behavior, we allow this probability to differ across groups. Visitors who see CTA A have a sign-up probability <span class="math inline">\(\pi_A\)</span>, while those who see CTA B have a probability <span class="math inline">\(\pi_B\)</span>. Each visitor’s outcome is therefore either 1 (sign-up) or 0 (no sign-up).</p>
<p>The quantity we care about is <span class="math inline">\(\theta = \pi_A - \pi_B\)</span>, which represents the difference in sign-up rates between the two CTAs.</p>
<p>To estimate this difference, we use the difference in sample means: <span class="math inline">\(\hat\theta = \bar{X}_A - \bar{X}_B\)</span>.</p>
<p>Since each observation is either 0 or 1, the sample mean is simply the proportion of visitors who signed up. This means <span class="math inline">\(\bar{X}_A = \hat\pi_A\)</span> and <span class="math inline">\(\bar{X}_B = \hat\pi_B\)</span>.</p>
</section>
<section id="simulating-data" class="level2">
<h2 class="anchored" data-anchor-id="simulating-data">Simulating Data</h2>
<p>In a real-world A/B test, we would not know the true values of <span class="math inline">\(\pi_A\)</span> and <span class="math inline">\(\pi_B\)</span>. However, for this exercise, we set them ourselves so that we can evaluate how well our estimator performs when the true value is known.</p>
<p>Suppose <span class="math inline">\(\pi_A = 0.22\)</span> and <span class="math inline">\(\pi_B = 0.18\)</span>, so the true difference in sign-up rates is <span class="math inline">\(\theta = 0.04\)</span>.</p>
<p>To simulate this scenario, we generate 1,000 observations for each group using Bernoulli distributions. Each observation represents whether a visitor signs up (1) or not (0). These simulated datasets will be used in the following sections to analyze the behavior of our estimator.</p>
</section>
<section id="the-law-of-large-numbers" class="level2">
<h2 class="anchored" data-anchor-id="the-law-of-large-numbers">The Law of Large Numbers</h2>
<p>The Law of Large Numbers states that as the sample size increases, the sample mean converges to the true population mean. In this context, it means that our estimator <span class="math inline">\(\hat\theta = \bar{X}_A - \bar{X}_B\)</span> will become closer to the true difference <span class="math inline">\(\theta\)</span> as we collect more data.</p>
<p>To demonstrate this, we compute the difference between the CTA A and CTA B outcomes for each observation, and then calculate the cumulative average of these differences as the sample size increases.</p>
<div id="797e5b8c" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-3-output-1.png" width="674" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The plot shows that when the number of observations is small, the estimate is very unstable and fluctuates significantly. This is because each new observation has a large impact on the average.</p>
<p>As more data is included, the estimate becomes smoother and stabilizes. Eventually, it converges toward the true value of 0.04.</p>
<p>This demonstrates the Law of Large Numbers: with a larger sample size, our estimate becomes more reliable and closer to the true difference.</p>
</section>
<section id="bootstrap-standard-errors" class="level2">
<h2 class="anchored" data-anchor-id="bootstrap-standard-errors">Bootstrap Standard Errors</h2>
<p>Now that we have an estimate of <span class="math inline">\(\theta\)</span>, the next question is how precise that estimate is. A point estimate tells us the most likely difference in sign-up rates, but it does not tell us how much uncertainty remains.</p>
<p>One useful way to measure that uncertainty is the bootstrap. The bootstrap is a resampling method: we repeatedly sample with replacement from the observed data, recompute the statistic each time, and then use the variation across those resampled estimates to approximate the standard error.</p>
<div id="209a5a77" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated difference (theta_hat): 0.0380
Bootstrap standard error:        0.0175
Analytical standard error:       0.0178
95% CI using bootstrap SE:       (0.0036, 0.0724)</code></pre>
</div>
</div>
<p>The bootstrap standard error (0.0175) is very close to the analytical standard error (0.0178), which suggests that the resampling method provides a reliable estimate of uncertainty.</p>
<p>Using the bootstrap standard error, we construct a 95% confidence interval for <span class="math inline">\(\theta\)</span> of (0.0036, 0.0724). This interval represents a range of plausible values for the true difference in sign-up rates between CTA A and CTA B.</p>
<p>Because the entire interval is above 0, this suggests that CTA A likely performs better than CTA B in this simulated example. In other words, there is evidence that the difference in sign-up rates is positive, not just due to random variation.</p>
</section>
<section id="the-central-limit-theorem" class="level2">
<h2 class="anchored" data-anchor-id="the-central-limit-theorem">The Central Limit Theorem</h2>
<p>The Central Limit Theorem states that regardless of the shape of the underlying population distribution, the sampling distribution of the sample mean becomes approximately Normal as the sample size increases. In this case, it means that the distribution of <span class="math inline">\(\hat\theta = \bar{X}_A - \bar{X}_B\)</span> will become more bell-shaped as the sample size grows.</p>
<p>To demonstrate this, we simulate the sampling distribution of <span class="math inline">\(\hat\theta\)</span> for different sample sizes: <span class="math inline">\(n \in \{25, 50, 100, 500\}\)</span>.</p>
<div id="ce4876ec" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-5-output-1.png" width="950" height="758" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The histograms show how the distribution of <span class="math inline">\(\hat\theta\)</span> changes as the sample size increases.</p>
<p>When the sample size is small (e.g., <span class="math inline">\(n = 25\)</span>), the distribution is irregular and somewhat noisy. The values are spread out and not clearly symmetric.</p>
<p>As the sample size increases (e.g., <span class="math inline">\(n = 50\)</span> and <span class="math inline">\(n = 100\)</span>), the distribution becomes smoother and more centered around the true value. The shape starts to look more balanced.</p>
<p>By the time we reach a large sample size (e.g., <span class="math inline">\(n = 500\)</span>), the distribution is clearly bell-shaped and tightly concentrated around the true value of 0.04.</p>
<p>This demonstrates the Central Limit Theorem: even though the underlying data are Bernoulli, the sampling distribution of the estimator becomes approximately Normal as the sample size grows.</p>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<p>Now that we have seen the Central Limit Theorem in action — that the sampling distribution of <span class="math inline">\(\hat\theta\)</span> is approximately Normal for large samples — we can use this result to perform a formal hypothesis test.</p>
<p>A hypothesis test is a way to determine whether the observed difference in sign-up rates is statistically significant or could have occurred by chance. We begin by defining our hypotheses. The null hypothesis is <span class="math inline">\(H_0: \theta = 0\)</span>, meaning that the two CTAs produce the same sign-up rate. The alternative hypothesis is <span class="math inline">\(H_1: \theta \neq 0\)</span>, meaning that there is a difference between the two CTAs. The goal is to assess whether the data provide enough evidence to reject <span class="math inline">\(H_0\)</span>.</p>
<p>To carry out the test, we standardize our estimator <span class="math inline">\(\hat\theta\)</span> to form a test statistic:</p>
<p><span class="math display">\[
z = \frac{\hat\theta - 0}{SE(\hat\theta)}
\]</span></p>
<p>This standardization step can be understood in three parts. First, by the Central Limit Theorem, we know that <span class="math inline">\(\hat\theta\)</span> is approximately Normally distributed when the sample size is large. Under the null hypothesis, the mean of this distribution is 0.</p>
<p>Second, when we divide a Normally distributed variable by its standard deviation, we obtain a standard Normal distribution <span class="math inline">\(N(0,1)\)</span>. Therefore, under <span class="math inline">\(H_0\)</span>, the test statistic <span class="math inline">\(z\)</span> follows an approximate standard Normal distribution.</p>
<p>Third, knowing the distribution of <span class="math inline">\(z\)</span> allows us to compute a p-value, which measures how extreme our observed result is under the assumption that the null hypothesis is true.</p>
<p>Although this procedure is often referred to as a “t-test”, it is more accurate to think of it as a z-test in this setting. The classical t-test applies when the data are Normally distributed and the variance must be estimated, leading to an exact t-distribution. In our case, the data are Bernoulli, not Normal, so there is no exact t-distribution result. Instead, the Central Limit Theorem provides approximate Normality. Since we estimate the standard error from the data, our test is conceptually closer to a z-test. In practice, for large samples, the t-distribution and the standard Normal distribution are very similar, so the difference is not important for our conclusions.</p>
<div id="4e334288" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>z-statistic: 2.1388
p-value:     0.0325</code></pre>
</div>
</div>
<p>The test statistic is 2.1388, which means our estimate is about 2.14 standard errors away from 0. The corresponding p-value is 0.0325.</p>
<p>Since the p-value is less than the common significance level of 0.05, we reject the null hypothesis <span class="math inline">\(H_0: \theta = 0\)</span>. This suggests that the difference in sign-up rates between the two CTAs is statistically significant.</p>
<p>In this simulated example, the result provides evidence that CTA A performs better than CTA B. The observed difference is unlikely to be due to random chance alone.</p>
</section>
<section id="the-t-test-as-a-regression" class="level2">
<h2 class="anchored" data-anchor-id="the-t-test-as-a-regression">The T-Test as a Regression</h2>
<p>It turns out that the two-sample test we just ran is mathematically equivalent to a simple linear regression. This connection is useful because it shows that the same regression tools used in many other settings can also be used to analyze A/B tests, and the framework extends naturally to more complex experiments.</p>
<p>To set this up, we combine the CTA A and CTA B data into one dataset with two variables. The outcome variable is <span class="math inline">\(Y_i\)</span>, which equals 1 if the visitor signs up and 0 otherwise. The second variable is an indicator <span class="math inline">\(D_i\)</span>, which equals 1 if the visitor saw CTA A and 0 if the visitor saw CTA B. We then fit the regression</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 D_i + \varepsilon_i
\]</span></p>
<p>This regression has a very direct interpretation. First, <span class="math inline">\(\beta_0\)</span> is the expected value of <span class="math inline">\(Y_i\)</span> when <span class="math inline">\(D_i = 0\)</span>. Since <span class="math inline">\(D_i = 0\)</span> corresponds to CTA B, <span class="math inline">\(\beta_0\)</span> is simply the mean sign-up rate in group B, which estimates <span class="math inline">\(\pi_B\)</span>.</p>
<p>Second, when <span class="math inline">\(D_i = 1\)</span>, the regression becomes <span class="math inline">\(\beta_0 + \beta_1\)</span>. This is the expected value of <span class="math inline">\(Y_i\)</span> for visitors who saw CTA A, so it represents the mean sign-up rate in group A, which estimates <span class="math inline">\(\pi_A\)</span>.</p>
<p>Third, if <span class="math inline">\(\beta_0\)</span> gives the mean of group B and <span class="math inline">\(\beta_0 + \beta_1\)</span> gives the mean of group A, then <span class="math inline">\(\beta_1\)</span> must be the difference between the two group means. That means</p>
<p><span class="math display">\[
\beta_1 = \pi_A - \pi_B = \theta
\]</span></p>
<p>and the OLS estimate <span class="math inline">\(\hat\beta_1\)</span> is numerically identical to the difference in sample means <span class="math inline">\(\hat\theta = \bar{X}_A - \bar{X}_B\)</span>.</p>
<div id="43625e43" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>beta_1 estimate: 0.0380
standard error:  0.0178
t-statistic:     2.1377
p-value:         0.0327
theta_hat:       0.0380</code></pre>
</div>
</div>
<p>The regression coefficient <span class="math inline">\(\hat\beta_1\)</span> is 0.0380, which exactly matches <span class="math inline">\(\hat\theta = 0.0380\)</span>. This confirms that the regression approach produces the same estimate as the difference in sample means.</p>
<p>The standard error (0.0178), t-statistic (2.1377), and p-value (0.0327) are also nearly identical to the values obtained in the previous hypothesis testing section. This shows that both approaches lead to the same statistical conclusion. Any small differences come from how the standard error is computed: the two-sample formula allows separate variances for each group, while OLS uses a pooled variance estimate.</p>
<p>This equivalence is important because it shows that regression provides a flexible and powerful framework for analyzing experiments. In simple cases like this, it gives the same result as a two-sample test. In more complex settings, it allows us to include additional variables, interactions, or multiple treatment groups, while maintaining the same interpretation of the results.</p>
</section>
<section id="the-problem-with-peeking" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-with-peeking">The Problem with Peeking</h2>
<p>In practice, it can be tempting to check results before an experiment is complete. Suppose we run our A/B test and instead of waiting for all 1,000 observations per group, we check the results every 100 observations. If any of those intermediate tests is significant at the <span class="math inline">\(\alpha = 0.05\)</span> level, we stop early and declare a winner.</p>
<p>This approach is problematic under classical frequentist statistics. A single hypothesis test at the 5% significance level has a 5% chance of producing a false positive (rejecting <span class="math inline">\(H_0\)</span> when it is actually true). However, when we repeatedly test the data as it accumulates, each check creates another opportunity for a false positive. As a result, the overall probability of making at least one false rejection becomes much higher than 5%.</p>
<p>To demonstrate this, we simulate a setting where the null hypothesis is true. We set <span class="math inline">\(\pi_A = \pi_B = 0.20\)</span>, meaning there is no real difference between the two CTAs.</p>
<div id="c3398100" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>False positive rate with peeking: 0.1864</code></pre>
</div>
</div>
<p>The simulation shows that the false positive rate with peeking is approximately 0.1864, or 18.64%. This is much higher than the nominal 5% false positive rate of a single hypothesis test.</p>
<p>This means that when we repeatedly check the data during the experiment, the chance of incorrectly rejecting the null hypothesis increases significantly. In other words, we are much more likely to conclude that one CTA is better when in reality there is no true difference.</p>
<p>This demonstrates that peeking inflates the Type I error rate and leads to unreliable conclusions. In practice, this means that stopping an experiment early based on intermediate results can produce misleading outcomes and should be avoided unless proper statistical adjustments are used.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>