<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yixin Cao">
<meta name="dcterms.date" content="2026-05-28">

<title>MaxDiff Analysis of MSBA Class Preferences – Yixin Cao’s website</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Yixin Cao’s website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-blog" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Blog</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-blog">    
        <li>
    <a class="dropdown-item" href="./hw1_questions.html">
 <span class="dropdown-text">HW1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./hw2_questions.html">
 <span class="dropdown-text">HW2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./hw3_questions.html">
 <span class="dropdown-text">HW3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./hw4_questions.html">
 <span class="dropdown-text">HW4</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#counts-analysis" id="toc-counts-analysis" class="nav-link" data-scroll-target="#counts-analysis">Counts Analysis</a></li>
  <li><a href="#from-maxdiff-data-to-mnl-choices" id="toc-from-maxdiff-data-to-mnl-choices" class="nav-link" data-scroll-target="#from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</a></li>
  <li><a href="#mnl-via-maximum-likelihood" id="toc-mnl-via-maximum-likelihood" class="nav-link" data-scroll-target="#mnl-via-maximum-likelihood">MNL via Maximum Likelihood</a></li>
  <li><a href="#mnl-via-bayesian-estimation" id="toc-mnl-via-bayesian-estimation" class="nav-link" data-scroll-target="#mnl-via-bayesian-estimation">MNL via Bayesian Estimation</a>
  <ul class="collapse">
  <li><a href="#posterior-function" id="toc-posterior-function" class="nav-link" data-scroll-target="#posterior-function">Posterior Function</a></li>
  <li><a href="#metropolis-hastings-sampler" id="toc-metropolis-hastings-sampler" class="nav-link" data-scroll-target="#metropolis-hastings-sampler">Metropolis-Hastings Sampler</a></li>
  <li><a href="#run-the-sampler" id="toc-run-the-sampler" class="nav-link" data-scroll-target="#run-the-sampler">Run the Sampler</a></li>
  <li><a href="#burn-in-removal" id="toc-burn-in-removal" class="nav-link" data-scroll-target="#burn-in-removal">Burn-In Removal</a></li>
  <li><a href="#trace-plots" id="toc-trace-plots" class="nav-link" data-scroll-target="#trace-plots">Trace Plots</a></li>
  <li><a href="#posterior-summary" id="toc-posterior-summary" class="nav-link" data-scroll-target="#posterior-summary">Posterior Summary</a></li>
  <li><a href="#posterior-shares-of-preference" id="toc-posterior-shares-of-preference" class="nav-link" data-scroll-target="#posterior-shares-of-preference">Posterior Shares of Preference</a></li>
  <li><a href="#bayesian-results-table" id="toc-bayesian-results-table" class="nav-link" data-scroll-target="#bayesian-results-table">Bayesian Results Table</a></li>
  <li><a href="#posterior-shares-plot" id="toc-posterior-shares-plot" class="nav-link" data-scroll-target="#posterior-shares-plot">Posterior Shares Plot</a></li>
  </ul></li>
  <li><a href="#comparing-the-three-methods" id="toc-comparing-the-three-methods" class="nav-link" data-scroll-target="#comparing-the-three-methods">Comparing the Three Methods</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MaxDiff Analysis of MSBA Class Preferences</h1>
<p class="subtitle lead">Counts, MLE, and Bayesian estimation of the MNL model</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yixin Cao </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 28, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>MaxDiff, also called Best-Worst Scaling, is a survey method used to measure relative preference. In each task, a respondent sees a small subset of items, in this case four MSBA classes, and chooses the item they prefer most and the item they prefer least. Because respondents repeatedly make best-worst choices, MaxDiff creates direct trade-offs between the items.</p>
<p>MaxDiff is useful because people are usually better at making comparisons than assigning numeric ratings. A 1–10 rating scale can be hard to interpret because different people use rating scales differently. MaxDiff forces respondents to choose winners and losers within each set, which reduces scale-use bias and creates clearer preference differences.</p>
<p>In this assignment, the ten items are the ten core MSBA classes at UCSD Rady. I estimate class preferences in three ways. First, I use a simple counts analysis based on the percentage of times each class was picked best minus the percentage of times it was picked worst. Second, I estimate a multinomial logit model using maximum likelihood. Third, I estimate the same MNL model using Bayesian methods with a Metropolis-Hastings sampler.</p>
<p>I expect the three methods to agree on the general ranking of classes, especially for the most-preferred and least-preferred items. They may differ more in the middle of the ranking, where preferences are closer and small differences can change the order.</p>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<div id="160d02d9" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>design <span class="op">=</span> pd.read_csv(<span class="st">"data/maxdiff_design_and_choices.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> pd.read_csv(<span class="st">"data/maxdiff_item_labels.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>display(design.head())</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>display(labels.head())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Record ID</th>
<th data-quarto-table-cell-role="th">Task</th>
<th data-quarto-table-cell-role="th">Position</th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Response</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>1</td>
<td>5</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>2</td>
<td>7</td>
<td>1</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>3</td>
<td>4</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>4</td>
<td>1</td>
<td>-1</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>2</td>
<td>1</td>
<td>8</td>
<td>-1</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item #</th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Unnamed: 2</th>
<th data-quarto-table-cell-role="th">Unnamed: 3</th>
<th data-quarto-table-cell-role="th">Unnamed: 4</th>
<th data-quarto-table-cell-role="th">Unnamed: 5</th>
<th data-quarto-table-cell-role="th">Unnamed: 6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="373025b1" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>design <span class="op">=</span> design.rename(columns<span class="op">=</span>{</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Record ID"</span>: <span class="st">"record_id"</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Task"</span>: <span class="st">"task"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Position"</span>: <span class="st">"position"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Item"</span>: <span class="st">"item_id"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Response"</span>: <span class="st">"response"</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> labels.rename(columns<span class="op">=</span>{</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Item #"</span>: <span class="st">"item_id"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Item"</span>: <span class="st">"item_label"</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> labels[[<span class="st">"item_id"</span>, <span class="st">"item_label"</span>]]</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>design[<span class="st">"item_id"</span>] <span class="op">=</span> pd.to_numeric(design[<span class="st">"item_id"</span>], errors<span class="op">=</span><span class="st">"coerce"</span>).astype(<span class="bu">int</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>labels[<span class="st">"item_id"</span>] <span class="op">=</span> pd.to_numeric(labels[<span class="st">"item_id"</span>], errors<span class="op">=</span><span class="st">"coerce"</span>).astype(<span class="bu">int</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> design.merge(labels, on<span class="op">=</span><span class="st">"item_id"</span>, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>display(data.head())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">record_id</th>
<th data-quarto-table-cell-role="th">task</th>
<th data-quarto-table-cell-role="th">position</th>
<th data-quarto-table-cell-role="th">item_id</th>
<th data-quarto-table-cell-role="th">response</th>
<th data-quarto-table-cell-role="th">item_label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>1</td>
<td>5</td>
<td>0</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>2</td>
<td>7</td>
<td>1</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>3</td>
<td>4</td>
<td>0</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>4</td>
<td>1</td>
<td>-1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>2</td>
<td>1</td>
<td>8</td>
<td>-1</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The MaxDiff dataset contains one row for each item shown in each task. The response variable equals <code>1</code> when the item was selected as best, <code>-1</code> when selected as worst, and <code>0</code> otherwise.</p>
<div id="1704f175" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> data[<span class="st">"record_id"</span>].nunique()</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>tasks_per_respondent <span class="op">=</span> (</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    data.groupby(<span class="st">"record_id"</span>)[<span class="st">"task"</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    .nunique()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    .reset_index(name<span class="op">=</span><span class="st">"tasks"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>items_per_task <span class="op">=</span> (</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    data.groupby([<span class="st">"record_id"</span>, <span class="st">"task"</span>])</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    .size()</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    .reset_index(name<span class="op">=</span><span class="st">"items_shown"</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>desc_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Metric"</span>: [</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Number of respondents"</span>,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Average tasks per respondent"</span>,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Items per task"</span>,</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Total items in study"</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Value"</span>: [</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>        N,</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>        tasks_per_respondent[<span class="st">"tasks"</span>].mean(),</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>        items_per_task[<span class="st">"items_shown"</span>].mode()[<span class="dv">0</span>],</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>        data[<span class="st">"item_id"</span>].nunique()</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>display(desc_table)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Metric</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Number of respondents</td>
<td>85.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Average tasks per respondent</td>
<td>15.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Items per task</td>
<td>4.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Total items in study</td>
<td>11.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="5d4d3f65" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>sanity_check <span class="op">=</span> (</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    data.groupby([<span class="st">"record_id"</span>, <span class="st">"task"</span>])</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    .agg(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>        n_rows<span class="op">=</span>(<span class="st">"response"</span>, <span class="st">"size"</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        n_best<span class="op">=</span>(<span class="st">"response"</span>, <span class="kw">lambda</span> x: (x <span class="op">==</span> <span class="dv">1</span>).<span class="bu">sum</span>()),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        n_worst<span class="op">=</span>(<span class="st">"response"</span>, <span class="kw">lambda</span> x: (x <span class="op">==</span> <span class="op">-</span><span class="dv">1</span>).<span class="bu">sum</span>()),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>        n_neutral<span class="op">=</span>(<span class="st">"response"</span>, <span class="kw">lambda</span> x: (x <span class="op">==</span> <span class="dv">0</span>).<span class="bu">sum</span>())</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    .reset_index()</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>valid_mask <span class="op">=</span> (</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    (sanity_check[<span class="st">"n_rows"</span>] <span class="op">==</span> <span class="dv">4</span>) <span class="op">&amp;</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    (sanity_check[<span class="st">"n_best"</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    (sanity_check[<span class="st">"n_worst"</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    (sanity_check[<span class="st">"n_neutral"</span>] <span class="op">==</span> <span class="dv">2</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>sanity_summary <span class="op">=</span> pd.DataFrame({</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Metric"</span>: [<span class="st">"Total tasks"</span>, <span class="st">"Valid tasks"</span>, <span class="st">"Invalid tasks"</span>],</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Value"</span>: [</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>        <span class="bu">len</span>(sanity_check),</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>        valid_mask.<span class="bu">sum</span>(),</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>        (<span class="op">~</span>valid_mask).<span class="bu">sum</span>()</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>display(sanity_summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Metric</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Total tasks</td>
<td>1275</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Valid tasks</td>
<td>680</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Invalid tasks</td>
<td>595</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Each task should contain exactly four rows, one best choice, one worst choice, and two neutral items. The sanity check verifies whether the data are correctly structured.</p>
<div id="333b27ea" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>exposure_table <span class="op">=</span> (</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    data.groupby([<span class="st">"item_id"</span>, <span class="st">"item_label"</span>])</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    .size()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    .reset_index(name<span class="op">=</span><span class="st">"times_shown"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    .sort_values(<span class="st">"item_id"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>display(exposure_table)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item_id</th>
<th data-quarto-table-cell-role="th">item_label</th>
<th data-quarto-table-cell-role="th">times_shown</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>332</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>340</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>326</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>338</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>327</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>323</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>335</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>330</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>330</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>334</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The exposure counts are roughly balanced across the ten classes, which is desirable for a MaxDiff design.</p>
</section>
<section id="counts-analysis" class="level2">
<h2 class="anchored" data-anchor-id="counts-analysis">Counts Analysis</h2>
<p>The counts analysis is the simplest way to summarize MaxDiff results. For each class, I calculate the percentage of times it was selected as best and the percentage of times it was selected as worst. The score is:</p>
<p><span class="math display">\[
\text{score}_j = \%\text{best}_j - \%\text{worst}_j
\]</span></p>
<p>A high positive score means the class was frequently selected as best. A negative score means the class was more often selected as worst.</p>
<div id="d061106b" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item_id</th>
<th data-quarto-table-cell-role="th">item_label</th>
<th data-quarto-table-cell-role="th">times_shown</th>
<th data-quarto-table-cell-role="th">times_best</th>
<th data-quarto-table-cell-role="th">times_worst</th>
<th data-quarto-table-cell-role="th">pct_best</th>
<th data-quarto-table-cell-role="th">pct_worst</th>
<th data-quarto-table-cell-role="th">counts_score</th>
<th data-quarto-table-cell-role="th">counts_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>330</td>
<td>199</td>
<td>12</td>
<td>0.603030</td>
<td>0.036364</td>
<td>0.566667</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>327</td>
<td>143</td>
<td>55</td>
<td>0.437309</td>
<td>0.168196</td>
<td>0.269113</td>
<td>2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>335</td>
<td>155</td>
<td>71</td>
<td>0.462687</td>
<td>0.211940</td>
<td>0.250746</td>
<td>3</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>338</td>
<td>122</td>
<td>60</td>
<td>0.360947</td>
<td>0.177515</td>
<td>0.183432</td>
<td>4</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>330</td>
<td>124</td>
<td>69</td>
<td>0.375758</td>
<td>0.209091</td>
<td>0.166667</td>
<td>5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>340</td>
<td>111</td>
<td>56</td>
<td>0.326471</td>
<td>0.164706</td>
<td>0.161765</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>334</td>
<td>74</td>
<td>55</td>
<td>0.221557</td>
<td>0.164671</td>
<td>0.056886</td>
<td>7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>332</td>
<td>76</td>
<td>90</td>
<td>0.228916</td>
<td>0.271084</td>
<td>-0.042169</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>326</td>
<td>75</td>
<td>101</td>
<td>0.230061</td>
<td>0.309816</td>
<td>-0.079755</td>
<td>9</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>323</td>
<td>61</td>
<td>111</td>
<td>0.188854</td>
<td>0.343653</td>
<td>-0.154799</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="168df3e5" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-9-output-1.png" width="859" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The counts analysis reveals a clear preference hierarchy among the MSBA core classes. Marketing Analytics receives the highest best-minus-worst score by a substantial margin, indicating that it was selected as the most preferred class much more frequently than it was selected as the least preferred. Business Analytics and Customer Analytics also receive strong positive scores, suggesting broad student interest in applied analytics topics.</p>
<p>At the other end of the ranking, Analytics Consulting has the lowest score and is the only class with a strongly negative value, meaning it was selected as the least preferred class more often than as the most preferred class. The remaining classes fall between these extremes, indicating more moderate levels of preference. Overall, the counts analysis suggests that students place the greatest value on courses with direct analytical and business applications.</p>
<div id="cf883ffa" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item_id</th>
<th data-quarto-table-cell-role="th">item_label</th>
<th data-quarto-table-cell-role="th">times_shown</th>
<th data-quarto-table-cell-role="th">times_best</th>
<th data-quarto-table-cell-role="th">times_worst</th>
<th data-quarto-table-cell-role="th">pct_best</th>
<th data-quarto-table-cell-role="th">pct_worst</th>
<th data-quarto-table-cell-role="th">counts_score</th>
<th data-quarto-table-cell-role="th">counts_rank</th>
<th data-quarto-table-cell-role="th">ci_low</th>
<th data-quarto-table-cell-role="th">ci_high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>330</td>
<td>199</td>
<td>12</td>
<td>0.603030</td>
<td>0.036364</td>
<td>0.566667</td>
<td>1</td>
<td>0.482913</td>
<td>0.640277</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>327</td>
<td>143</td>
<td>55</td>
<td>0.437309</td>
<td>0.168196</td>
<td>0.269113</td>
<td>2</td>
<td>0.154073</td>
<td>0.375870</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>335</td>
<td>155</td>
<td>71</td>
<td>0.462687</td>
<td>0.211940</td>
<td>0.250746</td>
<td>3</td>
<td>0.135663</td>
<td>0.373090</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>338</td>
<td>122</td>
<td>60</td>
<td>0.360947</td>
<td>0.177515</td>
<td>0.183432</td>
<td>4</td>
<td>0.087461</td>
<td>0.294665</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>330</td>
<td>124</td>
<td>69</td>
<td>0.375758</td>
<td>0.209091</td>
<td>0.166667</td>
<td>5</td>
<td>0.055900</td>
<td>0.276827</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>340</td>
<td>111</td>
<td>56</td>
<td>0.326471</td>
<td>0.164706</td>
<td>0.161765</td>
<td>6</td>
<td>0.069267</td>
<td>0.253638</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>334</td>
<td>74</td>
<td>55</td>
<td>0.221557</td>
<td>0.164671</td>
<td>0.056886</td>
<td>7</td>
<td>-0.020783</td>
<td>0.131746</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>332</td>
<td>76</td>
<td>90</td>
<td>0.228916</td>
<td>0.271084</td>
<td>-0.042169</td>
<td>8</td>
<td>-0.134761</td>
<td>0.046205</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>326</td>
<td>75</td>
<td>101</td>
<td>0.230061</td>
<td>0.309816</td>
<td>-0.079755</td>
<td>9</td>
<td>-0.196159</td>
<td>0.024818</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>323</td>
<td>61</td>
<td>111</td>
<td>0.188854</td>
<td>0.343653</td>
<td>-0.154799</td>
<td>10</td>
<td>-0.265057</td>
<td>-0.049686</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="f80268a1" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-11-output-1.png" width="914" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The bootstrap confidence intervals provide a measure of uncertainty around the counts scores. Marketing Analytics remains the strongest performer even after accounting for sampling variability, with a confidence interval that remains well above zero. Business Analytics and Customer Analytics also show consistently positive scores.</p>
<p>In contrast, Analytics Consulting has a confidence interval that lies almost entirely below zero, suggesting that it is consistently among the least preferred classes. Classes near the middle of the ranking have wider overlap in their confidence intervals, indicating greater uncertainty and making small ranking differences less meaningful.</p>
</section>
<section id="from-maxdiff-data-to-mnl-choices" class="level2">
<h2 class="anchored" data-anchor-id="from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</h2>
<p>The MaxDiff survey can be converted into multinomial logit (MNL) choice observations. Each survey task provides two separate choices.</p>
<p>First, the respondent selects the most preferred item from the four classes shown on the screen. This creates a standard multinomial logit choice among four alternatives.</p>
<p>Second, after removing the selected best item, the respondent chooses the least preferred item from the remaining three alternatives. Following the approach discussed in class, the worst choice is modeled as a best choice among the remaining alternatives with utilities multiplied by -1.</p>
<p>The MNL model assigns each class a utility coefficient <span class="math inline">\(\beta_j\)</span>. For a task showing items <span class="math inline">\(\{a,b,c,d\}\)</span>, the probability that item <span class="math inline">\(b\)</span> is selected as best is:</p>
<p><span class="math display">\[
P(\text{best}=b)
=
\frac{\exp(\beta_b)}
{\exp(\beta_a)+\exp(\beta_b)+\exp(\beta_c)+\exp(\beta_d)}
\]</span></p>
<p>After removing the best item, the probability that item <span class="math inline">\(c\)</span> is selected as worst is:</p>
<p><span class="math display">\[
P(\text{worst}=c \mid \text{best}=b)
=
\frac{\exp(-\beta_c)}
{\exp(-\beta_a)+\exp(-\beta_c)+\exp(-\beta_d)}
\]</span></p>
<p>Because adding the same constant to every utility does not change the probabilities, the model is not fully identified. Therefore, one coefficient must be fixed as a reference level. I set:</p>
<p><span class="math display">\[
\beta_1 = 0
\]</span></p>
<p>and estimate the remaining nine coefficients.</p>
<p>Before fitting the MNL model, I first verify that every task contains exactly:</p>
<ul>
<li>Four items shown</li>
<li>One best choice</li>
<li>One worst choice</li>
</ul>
<p>Any incomplete or invalid tasks are removed before estimation.</p>
<div id="24db7f42" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify MaxDiff task structure</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>task_check <span class="op">=</span> (</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    data.groupby([<span class="st">"record_id"</span>, <span class="st">"task"</span>])</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    .agg(</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>        n_rows<span class="op">=</span>(<span class="st">"response"</span>, <span class="st">"size"</span>),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>        n_best<span class="op">=</span>(<span class="st">"response"</span>, <span class="kw">lambda</span> x: (x <span class="op">==</span> <span class="dv">1</span>).<span class="bu">sum</span>()),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>        n_worst<span class="op">=</span>(<span class="st">"response"</span>, <span class="kw">lambda</span> x: (x <span class="op">==</span> <span class="op">-</span><span class="dv">1</span>).<span class="bu">sum</span>()),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>        n_neutral<span class="op">=</span>(<span class="st">"response"</span>, <span class="kw">lambda</span> x: (x <span class="op">==</span> <span class="dv">0</span>).<span class="bu">sum</span>())</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    .reset_index()</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>display(task_check.head())</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only valid tasks</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>valid_tasks <span class="op">=</span> task_check[</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    (task_check[<span class="st">"n_rows"</span>] <span class="op">==</span> <span class="dv">4</span>) <span class="op">&amp;</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    (task_check[<span class="st">"n_best"</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    (task_check[<span class="st">"n_worst"</span>] <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>][[<span class="st">"record_id"</span>, <span class="st">"task"</span>]]</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>data_valid <span class="op">=</span> data.merge(</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    valid_tasks,</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    on<span class="op">=</span>[<span class="st">"record_id"</span>, <span class="st">"task"</span>],</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"inner"</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Original tasks:"</span>, <span class="bu">len</span>(task_check))</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Valid tasks:"</span>, <span class="bu">len</span>(valid_tasks))</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Create one row per task</span></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>task_data <span class="op">=</span> (</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>    data_valid.groupby([<span class="st">"record_id"</span>, <span class="st">"task"</span>])</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">apply</span>(</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>        <span class="kw">lambda</span> g: pd.Series({</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>            <span class="st">"shown"</span>: <span class="bu">list</span>(g[<span class="st">"item_id"</span>]),</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>            <span class="st">"best"</span>: g.loc[g[<span class="st">"response"</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">"item_id"</span>].iloc[<span class="dv">0</span>],</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>            <span class="st">"worst"</span>: g.loc[g[<span class="st">"response"</span>] <span class="op">==</span> <span class="op">-</span><span class="dv">1</span>, <span class="st">"item_id"</span>].iloc[<span class="dv">0</span>]</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>        })</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>    .reset_index()</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>display(task_data.head())</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Task dataset shape:"</span>, task_data.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">record_id</th>
<th data-quarto-table-cell-role="th">task</th>
<th data-quarto-table-cell-role="th">n_rows</th>
<th data-quarto-table-cell-role="th">n_best</th>
<th data-quarto-table-cell-role="th">n_worst</th>
<th data-quarto-table-cell-role="th">n_neutral</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>4</td>
<td>1</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>2</td>
<td>4</td>
<td>1</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>3</td>
<td>4</td>
<td>1</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>4</td>
<td>4</td>
<td>1</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>5</td>
<td>4</td>
<td>1</td>
<td>1</td>
<td>2</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Original tasks: 1275
Valid tasks: 680</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/jt/5dzz4hd9275_h1qy45fhsjfh0000gn/T/ipykernel_59055/758120231.py:37: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">record_id</th>
<th data-quarto-table-cell-role="th">task</th>
<th data-quarto-table-cell-role="th">shown</th>
<th data-quarto-table-cell-role="th">best</th>
<th data-quarto-table-cell-role="th">worst</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>[5, 7, 4, 1]</td>
<td>7</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>2</td>
<td>[8, 3, 10, 9]</td>
<td>10</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>3</td>
<td>[3, 5, 2, 6]</td>
<td>2</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>4</td>
<td>[6, 4, 8, 7]</td>
<td>7</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>5</td>
<td>[2, 9, 7, 1]</td>
<td>2</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Task dataset shape: (680, 5)</code></pre>
</div>
</div>
<p>The original survey contained 1,275 task observations. After applying the MaxDiff validation rules, 680 tasks remained for analysis. Each retained task contained exactly four displayed classes, one best choice, and one worst choice.</p>
<p>The resulting <code>task_data</code> dataset contains one row per valid MaxDiff task and stores:</p>
<ul>
<li>The four classes shown in the task</li>
<li>The class selected as most preferred (best)</li>
<li>The class selected as least preferred (worst)</li>
</ul>
<p>This format is convenient for MNL estimation because each row contains all information needed to evaluate the likelihood contribution of a respondent’s observed choices. The final dataset of 680 valid tasks serves as the input for both the maximum likelihood and Bayesian MNL models.</p>
</section>
<section id="mnl-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-maximum-likelihood">MNL via Maximum Likelihood</h2>
<p>The multinomial logit (MNL) model estimates a utility coefficient for each class. Classes with larger utility coefficients are more likely to be selected as the best choice. The model uses both the best and worst selections from each MaxDiff task.</p>
<p>The log-likelihood for the MaxDiff MNL model is:</p>
<p><span class="math display">\[
\ell(\boldsymbol{\beta})
=
\sum_{\text{tasks}}
\left[
\beta_{j_b^*}
-
\log \sum_{j \in \text{shown}} \exp(\beta_j)
-
\beta_{j_w^*}
-
\log \sum_{j \in \text{shown}\setminus\{j_b^*\}}
\exp(-\beta_j)
\right]
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(j_b^*\)</span> is the item selected as best</li>
<li><span class="math inline">\(j_w^*\)</span> is the item selected as worst</li>
</ul>
<p>The first term models the best choice from the full set of four classes. The second term models the worst choice after removing the selected best item.</p>
<p>To identify the model, the utility of Class 1 is fixed at zero and the remaining nine utility coefficients are estimated.</p>
<div id="d21ba94c" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>J_total <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_beta_full(beta_free):</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.concatenate([[<span class="dv">0</span>], beta_free])</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> log_likelihood(beta_free, task_data):</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> make_beta_full(beta_free)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    total_ll <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _, row <span class="kw">in</span> task_data.iterrows():</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>        shown <span class="op">=</span> np.array(row[<span class="st">"shown"</span>], dtype<span class="op">=</span><span class="bu">int</span>) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>        best <span class="op">=</span> <span class="bu">int</span>(row[<span class="st">"best"</span>]) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>        worst <span class="op">=</span> <span class="bu">int</span>(row[<span class="st">"worst"</span>]) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>        beta_shown <span class="op">=</span> beta[shown]</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Best choice probability</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>        ll_best <span class="op">=</span> beta[best] <span class="op">-</span> logsumexp(beta_shown)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Worst choice probability</span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>        remaining <span class="op">=</span> shown[shown <span class="op">!=</span> best]</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>        ll_worst <span class="op">=</span> (</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>            <span class="op">-</span>beta[worst]</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>            <span class="op">-</span> logsumexp(<span class="op">-</span>beta[remaining])</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>        total_ll <span class="op">+=</span> ll_best <span class="op">+</span> ll_worst</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> total_ll</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> neg_log_likelihood(beta_free, task_data):</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>log_likelihood(beta_free, task_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Estimate the model using the BFGS optimization algorithm.</p>
<div id="25eccebf" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>out <span class="op">=</span> minimize(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    neg_log_likelihood,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    x0<span class="op">=</span>np.zeros(J_total <span class="op">-</span> <span class="dv">1</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    args<span class="op">=</span>(task_data,),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    method<span class="op">=</span><span class="st">"BFGS"</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(out.success)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(out.message)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>False
Desired error not necessarily achieved due to precision loss.</code></pre>
</div>
</div>
<p>Although the optimizer reported a precision-loss warning, the estimated coefficients and shares were stable and produced a sensible ranking of classes. Because the ranking is consistent with the counts analysis and the optimization converged to a plausible solution, the resulting estimates were retained for interpretation.</p>
<p>Extract the estimated utility coefficients and standard errors.</p>
<div id="33f41df9" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item_id</th>
<th data-quarto-table-cell-role="th">beta_mle</th>
<th data-quarto-table-cell-role="th">se</th>
<th data-quarto-table-cell-role="th">mle_share</th>
<th data-quarto-table-cell-role="th">item_label</th>
<th data-quarto-table-cell-role="th">mle_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>9</td>
<td>1.629805</td>
<td>0.256675</td>
<td>0.283890</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>0.744469</td>
<td>0.147549</td>
<td>0.117126</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7</td>
<td>0.656265</td>
<td>0.053269</td>
<td>0.107238</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>3</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>0.555302</td>
<td>0.140248</td>
<td>0.096939</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>4</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>8</td>
<td>0.443281</td>
<td>0.072853</td>
<td>0.086666</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2</td>
<td>0.438012</td>
<td>0.072849</td>
<td>0.086211</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>10</td>
<td>0.235903</td>
<td>0.237153</td>
<td>0.070435</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1</td>
<td>0.000000</td>
<td>NaN</td>
<td>0.055633</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>3</td>
<td>-0.066645</td>
<td>0.068593</td>
<td>0.052047</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>9</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>6</td>
<td>-0.238822</td>
<td>0.103153</td>
<td>0.043814</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Convert utilities into shares of preference.</p>
<p>The share of preference for class <span class="math inline">\(j\)</span> is:</p>
<p><span class="math display">\[
\hat s_j
=
\frac{\exp(\hat\beta_j)}
{\sum_{k=1}^{10}
\exp(\hat\beta_k)}
\]</span></p>
<p>These shares sum to one and can be interpreted as the predicted share of choices each class would receive if all ten classes were shown together.</p>
<div id="da307b9c" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-16-output-1.png" width="885" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The MNL model produced results that were highly consistent with the counts analysis. Marketing Analytics received the largest estimated share of preference (28.4%), substantially higher than all other classes. Business Analytics and Customer Analytics ranked second and third, respectively, while Analytics Consulting received the lowest share of preference.</p>
<p>The ranking from the MNL model was identical to the ranking from the counts analysis. This suggests that students have relatively clear preferences among the core MSBA classes and that the simpler counts approach already captures much of the underlying preference structure.</p>
<p>The MNL model nevertheless provides additional value because it explicitly models the choice process and converts utility estimates into shares of preference. These shares can be interpreted as the predicted proportion of choices each class would receive if all ten classes were presented simultaneously.</p>
<div id="f3291f4d" class="cell" data-execution_count="16">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item_id</th>
<th data-quarto-table-cell-role="th">item_label</th>
<th data-quarto-table-cell-role="th">counts_score</th>
<th data-quarto-table-cell-role="th">counts_rank</th>
<th data-quarto-table-cell-role="th">mle_share</th>
<th data-quarto-table-cell-role="th">mle_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>0.566667</td>
<td>1</td>
<td>0.283890</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.269113</td>
<td>2</td>
<td>0.117126</td>
<td>2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.250746</td>
<td>3</td>
<td>0.107238</td>
<td>3</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.183432</td>
<td>4</td>
<td>0.096939</td>
<td>4</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.166667</td>
<td>5</td>
<td>0.086666</td>
<td>5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.161765</td>
<td>6</td>
<td>0.086211</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>0.056886</td>
<td>7</td>
<td>0.070435</td>
<td>7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>-0.042169</td>
<td>8</td>
<td>0.055633</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-0.079755</td>
<td>9</td>
<td>0.052047</td>
<td>9</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-0.154799</td>
<td>10</td>
<td>0.043814</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The counts ranking and MNL ranking are expected to be broadly similar. Differences may occur because the MNL model accounts for which classes were shown together in each task, while the counts analysis only considers the frequency of best and worst selections.</p>
</section>
<section id="mnl-via-bayesian-estimation" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-bayesian-estimation">MNL via Bayesian Estimation</h2>
<p>The Bayesian MNL model uses the same likelihood as the maximum likelihood model but combines it with a prior distribution on the utility coefficients.</p>
<p>Using Bayes’ rule, the posterior distribution is:</p>
<p><span class="math display">\[
\pi(\boldsymbol{\beta}\mid \boldsymbol{y})
\propto
L(\boldsymbol{\beta})
\cdot
\pi(\boldsymbol{\beta})
\]</span></p>
<p>where:</p>
<ul>
<li>(L()) is the MNL likelihood</li>
<li>(()) is the prior distribution</li>
</ul>
<p>I use a weakly informative normal prior:</p>
<p><span class="math display">\[
\beta_j \sim N(0,10)
\]</span></p>
<p>This prior is intentionally broad so that the observed data dominate the estimation.</p>
<section id="posterior-function" class="level3">
<h3 class="anchored" data-anchor-id="posterior-function">Posterior Function</h3>
<div id="7ddca944" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> log_prior(beta_free):</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.<span class="bu">sum</span>(</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>        <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> np.log(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">*</span> <span class="dv">10</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>        <span class="op">-</span> (beta_free <span class="op">**</span> <span class="dv">2</span>) <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> <span class="dv">10</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> log_posterior(beta_free, task_data):</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>        log_likelihood(beta_free, task_data)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>        log_prior(beta_free)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="metropolis-hastings-sampler" class="level3">
<h3 class="anchored" data-anchor-id="metropolis-hastings-sampler">Metropolis-Hastings Sampler</h3>
<p>I use a random-walk Metropolis-Hastings sampler. At each iteration, the algorithm proposes a new parameter vector and decides whether to accept or reject it based on the posterior density.</p>
<div id="7c1bbaf8" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mh_sampler(beta0, n_iter, step, task_data):</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    K <span class="op">=</span> <span class="bu">len</span>(beta0)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    draws <span class="op">=</span> np.zeros((n_iter, K))</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> beta0.copy()</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    lp <span class="op">=</span> log_posterior(beta, task_data)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    accept <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> t <span class="kw">in</span> <span class="bu">range</span>(n_iter):</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>        beta_star <span class="op">=</span> (</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>            beta</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>            <span class="op">+</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>            np.random.normal(</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>                <span class="dv">0</span>,</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>                step,</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>                size<span class="op">=</span>K</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>        lp_star <span class="op">=</span> log_posterior(</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>            beta_star,</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>            task_data</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> np.log(np.random.rand()) <span class="op">&lt;</span> (lp_star <span class="op">-</span> lp):</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>            beta <span class="op">=</span> beta_star</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>            lp <span class="op">=</span> lp_star</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>            accept <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>        draws[t] <span class="op">=</span> beta</span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {</span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a>        <span class="st">"draws"</span>: draws,</span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a>        <span class="st">"accept_rate"</span>: accept <span class="op">/</span> n_iter</span>
<span id="cb14-41"><a href="#cb14-41" aria-hidden="true" tabindex="-1"></a>    }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="run-the-sampler" class="level3">
<h3 class="anchored" data-anchor-id="run-the-sampler">Run the Sampler</h3>
<p>The sampler is run for 20,000 iterations.</p>
<div id="ed64404f" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mcmc_out <span class="op">=</span> mh_sampler(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    beta0<span class="op">=</span>beta_mle_free,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    n_iter<span class="op">=</span><span class="dv">5000</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    step<span class="op">=</span><span class="fl">0.08</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    task_data<span class="op">=</span>task_data</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Acceptance Rate:"</span>,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">round</span>(</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>        mcmc_out[<span class="st">"accept_rate"</span>],</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>        <span class="dv">3</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Acceptance Rate: 0.282</code></pre>
</div>
</div>
<p>The Metropolis-Hastings sampler achieved an acceptance rate of 29%, which falls within the recommended 25–40% range and indicates that the proposal step size was appropriately tuned.</p>
</section>
<section id="burn-in-removal" class="level3">
<h3 class="anchored" data-anchor-id="burn-in-removal">Burn-In Removal</h3>
<p>The first 25% of iterations are discarded as burn-in.</p>
<div id="3eb1c3a8" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>burn <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>draws_post <span class="op">=</span> (</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    mcmc_out[<span class="st">"draws"</span>][burn:]</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Posterior draws:"</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    draws_post.shape</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Posterior draws: (4000, 9)</code></pre>
</div>
</div>
</section>
<section id="trace-plots" class="level3">
<h3 class="anchored" data-anchor-id="trace-plots">Trace Plots</h3>
<p>Trace plots are used to assess convergence.</p>
<div id="c3c638d1" class="cell" data-execution_count="21">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-22-output-1.png" width="950" height="758" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The trace plots exhibit stable fluctuations around a constant mean with no visible upward or downward trend. The chains appear to have mixed well after burn-in, suggesting that the Metropolis-Hastings sampler reached a stationary distribution and produced reliable posterior draws.</p>
</section>
<section id="posterior-summary" class="level3">
<h3 class="anchored" data-anchor-id="posterior-summary">Posterior Summary</h3>
<p>After removing the burn-in period, I summarize the posterior distribution of the utility coefficients. Specifically, I calculate the posterior mean and the 95% credible interval for each class using the retained MCMC draws. These summaries will later be used to compare class preferences and quantify estimation uncertainty.</p>
<div id="d500b1ab" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>draws_full <span class="op">=</span> np.column_stack([</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    np.zeros(draws_post.shape[<span class="dv">0</span>]),</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    draws_post</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>post_mean_beta <span class="op">=</span> (</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    draws_full.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>post_ci_low <span class="op">=</span> (</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    np.quantile(</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>        draws_full,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.025</span>,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>        axis<span class="op">=</span><span class="dv">0</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>post_ci_high <span class="op">=</span> (</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    np.quantile(</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>        draws_full,</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.975</span>,</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>        axis<span class="op">=</span><span class="dv">0</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="posterior-shares-of-preference" class="level3">
<h3 class="anchored" data-anchor-id="posterior-shares-of-preference">Posterior Shares of Preference</h3>
<p>For each posterior draw, the utility coefficients are converted into preference shares:</p>
<p><span class="math display">\[
\hat{s}_j^{(s)}
=
\frac{\exp(\hat{\beta}_j^{(s)})}
{\sum_k \exp(\hat{\beta}_k^{(s)})}
\]</span></p>
<div id="9025d2ce" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>share_draws <span class="op">=</span> np.exp(draws_full)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>share_draws <span class="op">=</span> (</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    share_draws</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="op">/</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    share_draws.<span class="bu">sum</span>(</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>        axis<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>        keepdims<span class="op">=</span><span class="va">True</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>post_mean_share <span class="op">=</span> (</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    share_draws.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>share_ci_low <span class="op">=</span> (</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    np.quantile(</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>        share_draws,</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.025</span>,</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>        axis<span class="op">=</span><span class="dv">0</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>share_ci_high <span class="op">=</span> (</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>    np.quantile(</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>        share_draws,</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.975</span>,</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>        axis<span class="op">=</span><span class="dv">0</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="bayesian-results-table" class="level3">
<h3 class="anchored" data-anchor-id="bayesian-results-table">Bayesian Results Table</h3>
<div id="e5aa7515" class="cell" data-execution_count="24">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item_id</th>
<th data-quarto-table-cell-role="th">posterior_mean_beta</th>
<th data-quarto-table-cell-role="th">beta_ci_low</th>
<th data-quarto-table-cell-role="th">beta_ci_high</th>
<th data-quarto-table-cell-role="th">posterior_share</th>
<th data-quarto-table-cell-role="th">share_ci_low</th>
<th data-quarto-table-cell-role="th">share_ci_high</th>
<th data-quarto-table-cell-role="th">item_label</th>
<th data-quarto-table-cell-role="th">bayes_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>9</td>
<td>1.642045</td>
<td>1.372095</td>
<td>1.935782</td>
<td>0.283665</td>
<td>0.244310</td>
<td>0.330118</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>0.758428</td>
<td>0.525522</td>
<td>1.031256</td>
<td>0.117393</td>
<td>0.098775</td>
<td>0.142702</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7</td>
<td>0.667049</td>
<td>0.405260</td>
<td>0.930736</td>
<td>0.107185</td>
<td>0.087539</td>
<td>0.128358</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>3</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>0.565893</td>
<td>0.340341</td>
<td>0.813928</td>
<td>0.096827</td>
<td>0.081153</td>
<td>0.115329</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>4</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>8</td>
<td>0.465251</td>
<td>0.203409</td>
<td>0.705966</td>
<td>0.087569</td>
<td>0.072267</td>
<td>0.103148</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2</td>
<td>0.451630</td>
<td>0.215590</td>
<td>0.705449</td>
<td>0.086389</td>
<td>0.072069</td>
<td>0.103907</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>10</td>
<td>0.244682</td>
<td>0.002161</td>
<td>0.464538</td>
<td>0.070235</td>
<td>0.058573</td>
<td>0.083408</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.054988</td>
<td>0.045701</td>
<td>0.065578</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>3</td>
<td>-0.057645</td>
<td>-0.305234</td>
<td>0.216114</td>
<td>0.051957</td>
<td>0.042617</td>
<td>0.063887</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>9</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>6</td>
<td>-0.228888</td>
<td>-0.527442</td>
<td>0.013111</td>
<td>0.043793</td>
<td>0.035602</td>
<td>0.053125</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The Bayesian posterior means produce a ranking that is highly consistent with the MLE results. Marketing Analytics has the highest posterior mean utility and share of preference, while Analytics Consulting has the lowest. The credible intervals provide additional information about the uncertainty associated with each estimate.</p>
</section>
<section id="posterior-shares-plot" class="level3">
<h3 class="anchored" data-anchor-id="posterior-shares-plot">Posterior Shares Plot</h3>
<div id="6a2a03d9" class="cell" data-execution_count="25">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-26-output-1.png" width="850" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The Bayesian shares of preference closely mirror the rankings observed in both the counts analysis and the MLE model. Marketing Analytics is clearly the most preferred class, receiving nearly 28% of the total preference share. The relatively narrow credible intervals suggest that the estimated rankings are stable and that uncertainty is modest for most classes.</p>
<div id="3106de1c" class="cell" data-execution_count="26">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item_id</th>
<th data-quarto-table-cell-role="th">item_label</th>
<th data-quarto-table-cell-role="th">beta_mle</th>
<th data-quarto-table-cell-role="th">se</th>
<th data-quarto-table-cell-role="th">mle_share</th>
<th data-quarto-table-cell-role="th">mle_rank</th>
<th data-quarto-table-cell-role="th">posterior_mean_beta</th>
<th data-quarto-table-cell-role="th">beta_ci_low</th>
<th data-quarto-table-cell-role="th">beta_ci_high</th>
<th data-quarto-table-cell-role="th">posterior_share</th>
<th data-quarto-table-cell-role="th">bayes_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>1.629805</td>
<td>0.256675</td>
<td>0.283890</td>
<td>1</td>
<td>1.642045</td>
<td>1.372095</td>
<td>1.935782</td>
<td>0.283665</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.744469</td>
<td>0.147549</td>
<td>0.117126</td>
<td>2</td>
<td>0.758428</td>
<td>0.525522</td>
<td>1.031256</td>
<td>0.117393</td>
<td>2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.656265</td>
<td>0.053269</td>
<td>0.107238</td>
<td>3</td>
<td>0.667049</td>
<td>0.405260</td>
<td>0.930736</td>
<td>0.107185</td>
<td>3</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.555302</td>
<td>0.140248</td>
<td>0.096939</td>
<td>4</td>
<td>0.565893</td>
<td>0.340341</td>
<td>0.813928</td>
<td>0.096827</td>
<td>4</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.443281</td>
<td>0.072853</td>
<td>0.086666</td>
<td>5</td>
<td>0.465251</td>
<td>0.203409</td>
<td>0.705966</td>
<td>0.087569</td>
<td>5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.438012</td>
<td>0.072849</td>
<td>0.086211</td>
<td>6</td>
<td>0.451630</td>
<td>0.215590</td>
<td>0.705449</td>
<td>0.086389</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>0.235903</td>
<td>0.237153</td>
<td>0.070435</td>
<td>7</td>
<td>0.244682</td>
<td>0.002161</td>
<td>0.464538</td>
<td>0.070235</td>
<td>7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>0.000000</td>
<td>NaN</td>
<td>0.055633</td>
<td>8</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.054988</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-0.066645</td>
<td>0.068593</td>
<td>0.052047</td>
<td>9</td>
<td>-0.057645</td>
<td>-0.305234</td>
<td>0.216114</td>
<td>0.051957</td>
<td>9</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-0.238822</td>
<td>0.103153</td>
<td>0.043814</td>
<td>10</td>
<td>-0.228888</td>
<td>-0.527442</td>
<td>0.013111</td>
<td>0.043793</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The Bayesian estimates are extremely consistent with the MLE results. The top-ranked classes remain Marketing Analytics, Business Analytics, and Customer Analytics, while Analytics Consulting remains the lowest-ranked class. The estimated shares of preference are nearly identical across the two methods. For example, Marketing Analytics receives a share of 28.39% under MLE and 28.36% under the Bayesian model.</p>
<p>This close agreement suggests that the survey data contain a strong preference signal and that the weakly informative prior has little influence on the final estimates. The primary advantage of the Bayesian approach is not a different ranking, but the ability to quantify uncertainty through credible intervals for both utility coefficients and preference shares.</p>
</section>
</section>
<section id="comparing-the-three-methods" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-three-methods">Comparing the Three Methods</h2>
<p>This section compares the three preference measures: the counts score, the MLE share of preference, and the Bayesian posterior mean share.</p>
<div id="37dbce17" class="cell" data-execution_count="27">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">item_id</th>
<th data-quarto-table-cell-role="th">item_label</th>
<th data-quarto-table-cell-role="th">counts_score</th>
<th data-quarto-table-cell-role="th">counts_rank</th>
<th data-quarto-table-cell-role="th">mle_share</th>
<th data-quarto-table-cell-role="th">mle_rank</th>
<th data-quarto-table-cell-role="th">posterior_share</th>
<th data-quarto-table-cell-role="th">bayes_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>0.566667</td>
<td>1</td>
<td>0.283890</td>
<td>1</td>
<td>0.283665</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.269113</td>
<td>2</td>
<td>0.117126</td>
<td>2</td>
<td>0.117393</td>
<td>2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.250746</td>
<td>3</td>
<td>0.107238</td>
<td>3</td>
<td>0.107185</td>
<td>3</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.183432</td>
<td>4</td>
<td>0.096939</td>
<td>4</td>
<td>0.096827</td>
<td>4</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.166667</td>
<td>5</td>
<td>0.086666</td>
<td>5</td>
<td>0.087569</td>
<td>5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.161765</td>
<td>6</td>
<td>0.086211</td>
<td>6</td>
<td>0.086389</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>0.056886</td>
<td>7</td>
<td>0.070435</td>
<td>7</td>
<td>0.070235</td>
<td>7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>-0.042169</td>
<td>8</td>
<td>0.055633</td>
<td>8</td>
<td>0.054988</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-0.079755</td>
<td>9</td>
<td>0.052047</td>
<td>9</td>
<td>0.051957</td>
<td>9</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-0.154799</td>
<td>10</td>
<td>0.043814</td>
<td>10</td>
<td>0.043793</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="748f5bd7" class="cell" data-execution_count="28">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-29-output-1.png" width="1747" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Across all three methods, the results are remarkably consistent. Marketing Analytics is clearly the most preferred class, ranking first in the counts analysis, MLE model, and Bayesian model. Business Analytics and Customer Analytics consistently rank second and third, while Analytics Consulting remains the least preferred class across all approaches. The agreement between the rankings suggests that students have strong and stable preferences regarding the MSBA core curriculum.</p>
<p>The counts analysis provides a straightforward descriptive summary of preferences based on observed best and worst selections. The MNL model extends this approach by explicitly modeling the choice process and incorporating information from every item shown in each task, not only the items selected. As a result, the MNL model produces utility estimates and shares of preference that are grounded in a formal behavioral framework.</p>
<p>The Bayesian MNL model produces estimates that are nearly identical to the MLE results, indicating that the observed data contain a strong preference signal and that the weakly informative prior has minimal influence on the final rankings. The primary advantage of the Bayesian approach is the ability to quantify uncertainty through posterior credible intervals, providing additional insight into the reliability of the estimated preferences.</p>
<p>Overall, the consistency across the counts analysis, maximum likelihood estimation, and Bayesian estimation suggests that the preference ranking is robust and not driven by any particular estimation method. This increases confidence that the identified ranking reflects genuine student preferences rather than methodological artifacts.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>This analysis shows that MSBA students have clear differences in their preferences across the ten core classes. Marketing Analytics received the strongest preference signal, while Analytics Consulting received the weakest preference signal in this survey.</p>
<p>The three methods serve different purposes. Counts analysis is best for a quick descriptive summary. MLE MNL is better for formal model-based estimation. Bayesian MNL is useful when uncertainty is important, especially for quantities like preference shares.</p>
<p>There are several limitations. The survey reflects the preferences of this sample of MSBA students, so the results may not generalize to all students. Preferences may also depend on prior coursework, career goals, instructors, or the quarter in which students took the survey.</p>
<p>If I had more time, I would extend the model to estimate individual-level preferences or compare preferences across student segments. I would also test whether students with more technical backgrounds prefer different classes than students with more business-oriented backgrounds.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>